/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all todos for the current user */
        get: operations["getTodos"];
        put?: never;
        /** Create a new todo */
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a todo by ID */
        get: operations["getTodo"];
        /** Update a todo */
        put: operations["updateTodo"];
        post?: never;
        /** Delete a todo */
        delete: operations["deleteTodo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a todo as completed */
        post: operations["completeTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen a completed todo */
        post: operations["reopenTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get overdue todos */
        get: operations["getOverdueTodos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get today's todos */
        get: operations["getTodayTodos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/week": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get this week's todos */
        get: operations["getThisWeekTodos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search todos with filters */
        get: operations["searchTodos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get todo statistics */
        get: operations["getTodoStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            error: string;
            message?: string | null;
            details?: string | null;
        };
        Todo: {
            id: number;
            name: string;
            /** @description Nullable. Optional long text. */
            description?: string | null;
            /** @enum {string} */
            status: "todo" | "in_progress" | "done";
            /** @enum {string} */
            priority: "low" | "medium" | "high";
            /**
             * Format: date-time
             * @description Nullable. Due date can be omitted.
             */
            due_date?: string | null;
            user_id: number;
            /** @description Nullable. Unset when no category. */
            category_id?: number | null;
            /** @description Nullable. Unset when no parent. */
            parent_todo_id?: number | null;
            /** @description Nullable. Unset when no project. */
            project_id?: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateTodoInput: {
            name: string;
            /** @description Nullable. Optional long text. */
            description?: string | null;
            /** @enum {string} */
            status?: "todo" | "in_progress" | "done";
            /** @enum {string} */
            priority?: "low" | "medium" | "high";
            /**
             * Format: date-time
             * @description Nullable. Due date can be omitted.
             */
            due_date?: string | null;
            /** @description Nullable. Unset when no category. */
            category_id?: number | null;
            /** @description Nullable. Unset when no parent. */
            parent_todo_id?: number | null;
            /** @description Nullable. Unset when no project. */
            project_id?: number | null;
            tag_ids?: number[];
        };
        UpdateTodoInput: {
            /** @description Nullable. Omit to keep current value. */
            name?: string | null;
            /** @description Nullable. Omit to keep current value. */
            description?: string | null;
            /**
             * @description Nullable. Omit to keep current value.
             * @enum {string|null}
             */
            status?: "todo" | "in_progress" | "done" | null;
            /**
             * @description Nullable. Omit to keep current value.
             * @enum {string|null}
             */
            priority?: "low" | "medium" | "high" | null;
            /**
             * Format: date-time
             * @description Nullable. Omit to keep current value.
             */
            due_date?: string | null;
            /** @description Nullable. Omit to keep current value. */
            category_id?: number | null;
            /** @description Nullable. Omit to keep current value. */
            parent_todo_id?: number | null;
            /** @description Nullable. Omit to keep current value. */
            project_id?: number | null;
            /** @description Nullable. Omit to keep current value. */
            tag_ids?: number[] | null;
        };
        SearchResult: {
            todos: components["schemas"]["Todo"][];
            total: number;
            page: number;
            limit: number;
            total_pages: number;
        };
        Statistics: {
            total_count: number;
            status_counts: {
                [key: string]: number;
            };
            priority_counts: {
                [key: string]: number;
            };
            overdue_count: number;
            due_today_count: number;
            due_this_week_count: number;
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Unauthorized */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Not Found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        TodoId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getTodos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    getTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    updateTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTodoInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    deleteTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    completeTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    reopenTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getOverdueTodos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    getTodayTodos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    getThisWeekTodos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    searchTodos: {
        parameters: {
            query?: {
                status?: "todo" | "in_progress" | "done";
                priority?: "low" | "medium" | "high";
                category_id?: number;
                tag_ids?: number[];
                search?: string;
                due_from?: string;
                due_to?: string;
                sort?: "due_date" | "priority" | "created_at";
                order?: "asc" | "desc";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    getTodoStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statistics"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
}
